#!/usr/bin/env bash
# generate-replit-ci.sh — reads .replit + replit.nix and generates CI parity files
#
# Usage:
#   ./scripts/generate-replit-ci.sh                    # generate all files
#   ./scripts/generate-replit-ci.sh --dry-run          # preview without writing
#   ./scripts/generate-replit-ci.sh --only workflow    # just the GitHub workflow
#
# Detects from your existing config:
#   - Node version from replit.nix (20, 22, etc.)
#   - Build command from .replit [deployment]
#   - Port from .replit [[ports]]
#   - Project structure (monorepo dirs with package.json)

set -euo pipefail

DRY_RUN=false
ONLY=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run) DRY_RUN=true; shift ;;
    --only) ONLY="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# --- Detect from .replit ---

NODE_VERSION="22"  # default
if [ -f replit.nix ]; then
  # Extract nodejs version: pkgs.nodejs_22 → 22
  DETECTED=$(grep -oP 'nodejs_\K\d+' replit.nix 2>/dev/null || true)
  if [ -n "$DETECTED" ]; then
    NODE_VERSION="$DETECTED"
  else
    # Check for plain nodejs (no version suffix)
    if grep -q 'pkgs.nodejs' replit.nix && ! grep -q 'pkgs.nodejs_' replit.nix; then
      NODE_VERSION="20"  # default Nix nodejs
    fi
  fi
fi

# Detect port from .replit
PORT="3001"
if [ -f .replit ]; then
  DETECTED_PORT=$(grep -oP 'localPort\s*=\s*\K\d+' .replit 2>/dev/null | head -1 || true)
  if [ -n "$DETECTED_PORT" ]; then
    PORT="$DETECTED_PORT"
  fi
fi

# Detect build steps from .replit
# Look for [deployment] build command
BUILD_CMD=""
if [ -f .replit ]; then
  # Try to extract the shell build command
  BUILD_CMD=$(awk '/\[deployment\]/{found=1} found && /build.*=.*sh.*-c/{getline; if(/"/) {gsub(/^"|"$/, ""); print; exit}}' .replit 2>/dev/null || true)
fi

# Detect project structure
HAS_PWA=false
HAS_BACKEND=false
HAS_AUTOREGULATE=false
[ -d pwa ] && HAS_PWA=true
[ -d backend ] && HAS_BACKEND=true
[ -d autoregulate ] && HAS_AUTOREGULATE=true

# For single-dir projects (no pwa/backend split)
HAS_SINGLE=false
if [ -f package.json ] && [ "$HAS_PWA" = false ] && [ "$HAS_BACKEND" = false ]; then
  HAS_SINGLE=true
fi

echo "Detected configuration:"
echo "  Node version:  $NODE_VERSION"
echo "  Port:          $PORT"
echo "  PWA dir:       $HAS_PWA"
echo "  Backend dir:   $HAS_BACKEND"
echo "  Autoregulate:  $HAS_AUTOREGULATE"
echo "  Single project: $HAS_SINGLE"
if [ -n "$BUILD_CMD" ]; then
  echo "  Build command: $BUILD_CMD"
fi
echo ""

# --- Generate GitHub Actions Workflow ---

generate_workflow() {
  cat <<WORKFLOW
# Replit Parity CI — validates that code will work on Replit before merge
#
# Auto-generated by scripts/generate-replit-ci.sh
# Matches Node $NODE_VERSION from replit.nix and build sequence from .replit

name: Replit Parity

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    env:
      PORT: $PORT

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node $NODE_VERSION (matches replit.nix)
        uses: actions/setup-node@v4
        with:
          node-version: '$NODE_VERSION'
          cache: 'npm'
WORKFLOW

  # Generate cache-dependency-path based on structure
  if [ "$HAS_PWA" = true ] && [ "$HAS_BACKEND" = true ]; then
    cat <<WORKFLOW
          cache-dependency-path: |
            backend/package-lock.json
            pwa/package-lock.json
WORKFLOW
  elif [ "$HAS_SINGLE" = true ]; then
    cat <<WORKFLOW
          cache-dependency-path: package-lock.json
WORKFLOW
  fi

  # Generate build steps based on project structure
  # Mirror the .replit [deployment] build order
  if [ "$HAS_PWA" = true ]; then
    cat <<WORKFLOW

      # --- PWA build ---
      - name: PWA — install
        working-directory: pwa
        run: npm install

      - name: PWA — typecheck
        continue-on-error: true
        working-directory: pwa
        run: npx tsc -b

      - name: PWA — build
        working-directory: pwa
        run: npm run build
WORKFLOW
  fi

  if [ "$HAS_BACKEND" = true ]; then
    cat <<WORKFLOW

      # --- Backend build ---
      - name: Backend — install
        working-directory: backend
        run: npm install

      - name: Backend — typecheck
        continue-on-error: true
        working-directory: backend
        run: npx tsc --noEmit

      - name: Backend — build
        working-directory: backend
        run: npm run build
WORKFLOW
  fi

  if [ "$HAS_SINGLE" = true ]; then
    cat <<WORKFLOW

      # --- Build ---
      - name: Install
        run: npm install

      - name: Typecheck
        continue-on-error: true
        run: npx tsc -b

      - name: Build
        run: npm run build
WORKFLOW
  fi

  # Validate build output
  cat <<WORKFLOW

      # --- Validate build output ---
WORKFLOW

  if [ "$HAS_PWA" = true ]; then
    cat <<WORKFLOW
      - name: Check PWA assets exist
        run: |
          ASSETS=\$(ls pwa/dist/assets/ 2>/dev/null | wc -l)
          echo "Asset files: \$ASSETS"
          if [ "\$ASSETS" -eq 0 ]; then
            echo "::error::No assets in pwa/dist/assets/ — PWA build produced nothing"
            exit 1
          fi

      - name: Check PWA index.html
        run: |
          if [ ! -f pwa/dist/index.html ]; then
            echo "::error::pwa/dist/index.html missing — Vite build failed silently"
            exit 1
          fi
          if ! grep -q 'src=' pwa/dist/index.html; then
            echo "::error::index.html has no JS script references — build is broken"
            exit 1
          fi
WORKFLOW
  fi

  if [ "$HAS_BACKEND" = true ]; then
    cat <<WORKFLOW
      - name: Check backend dist exists
        run: |
          if [ ! -f backend/dist/index.js ]; then
            echo "::error::backend/dist/index.js missing — backend build failed"
            exit 1
          fi
WORKFLOW
  fi

  if [ "$HAS_SINGLE" = true ]; then
    cat <<WORKFLOW
      - name: Check dist exists
        run: |
          if [ ! -d dist ]; then
            echo "::error::dist/ missing — build failed"
            exit 1
          fi
WORKFLOW
  fi

  # Runtime serve test
  if [ "$HAS_BACKEND" = true ]; then
    cat <<WORKFLOW

      # --- Runtime serve test ---
      - name: Start backend + verify app serves
        continue-on-error: true
        run: |
          cd backend && NODE_ENV=production node dist/index.js &
          SERVER_PID=\$!

          for i in \$(seq 1 10); do
            if curl -sf http://localhost:$PORT/api/health > /dev/null 2>&1; then
              echo "Server is up"
              break
            fi
            if [ "\$i" -eq 10 ]; then
              echo "::warning::Server did not start within 10s (may need DATABASE_URL)"
              kill \$SERVER_PID 2>/dev/null
              exit 1
            fi
            sleep 1
          done

          HTTP_CODE=\$(curl -sf -o /dev/null -w '%{http_code}' http://localhost:$PORT/)
          if [ "\$HTTP_CODE" = "200" ]; then
            echo "App serves correctly (HTTP 200)"
          else
            echo "::warning::App returned HTTP \$HTTP_CODE (expected 200)"
          fi

          kill \$SERVER_PID 2>/dev/null
WORKFLOW
  fi
}

# --- Generate Dockerfile ---

generate_dockerfile() {
  cat <<DOCKERFILE
# Mirrors Replit's Node $NODE_VERSION environment
# Build + serve sequence matches .replit [deployment] exactly

FROM node:${NODE_VERSION}-bookworm AS builder

WORKDIR /app
DOCKERFILE

  if [ "$HAS_PWA" = true ] && [ "$HAS_BACKEND" = true ]; then
    cat <<DOCKERFILE

# --- PWA build ---
COPY pwa/package.json pwa/package-lock.json* ./pwa/
WORKDIR /app/pwa
RUN npm install
COPY pwa/ ./
RUN npm run build

# --- Backend build ---
WORKDIR /app
COPY backend/package.json backend/package-lock.json* ./backend/
WORKDIR /app/backend
RUN npm install
COPY backend/ ./
RUN npm run build

# --- Production image ---
FROM node:${NODE_VERSION}-bookworm-slim

WORKDIR /app

COPY --from=builder /app/backend/dist ./backend/dist
COPY --from=builder /app/backend/node_modules ./backend/node_modules
COPY --from=builder /app/backend/package.json ./backend/package.json
COPY --from=builder /app/pwa/dist ./pwa/dist

ENV PORT=$PORT
ENV NODE_ENV=production
EXPOSE $PORT

CMD ["node", "backend/dist/index.js"]
DOCKERFILE
  elif [ "$HAS_SINGLE" = true ]; then
    cat <<DOCKERFILE

COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build

# --- Production image ---
FROM node:${NODE_VERSION}-bookworm-slim

WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

ENV PORT=$PORT
ENV NODE_ENV=production
EXPOSE $PORT

CMD ["node", "dist/index.js"]
DOCKERFILE
  fi
}

# --- Generate .dockerignore ---

generate_dockerignore() {
  cat <<DOCKERIGNORE
node_modules
dist
.env
*.log
.DS_Store
.autoregulate/
*.md
.git/
.gitignore
.replit
replit.nix
DOCKERIGNORE
}

# --- Generate pre-push hook ---

generate_prepush() {
  cat <<PREPUSH
#!/usr/bin/env bash
# Pre-push check — lightweight local validation (no Docker required)
# Install: ln -sf ../../scripts/pre-push.sh .git/hooks/pre-push

set -euo pipefail

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

ERRORS=0
echo -e "\${YELLOW}▶ Pre-push: checking Replit parity...\${NC}"
PREPUSH

  if [ "$HAS_BACKEND" = true ]; then
    cat <<PREPUSH

echo -e "\${YELLOW}  backend: tsc --noEmit\${NC}"
if (cd backend && npx tsc --noEmit 2>&1); then
  echo -e "\${GREEN}  ✓ backend typecheck\${NC}"
else
  echo -e "\${RED}  ✗ backend typecheck failed\${NC}"
  ERRORS=\$((ERRORS + 1))
fi
PREPUSH
  fi

  if [ "$HAS_PWA" = true ]; then
    cat <<PREPUSH

echo -e "\${YELLOW}  pwa: tsc -b\${NC}"
if (cd pwa && npx tsc -b 2>&1); then
  echo -e "\${GREEN}  ✓ pwa typecheck\${NC}"
else
  echo -e "\${RED}  ✗ pwa typecheck failed\${NC}"
  ERRORS=\$((ERRORS + 1))
fi

echo -e "\${YELLOW}  pwa: vite build (production)\${NC}"
if (cd pwa && npx vite build 2>&1); then
  echo -e "\${GREEN}  ✓ pwa build\${NC}"
else
  echo -e "\${RED}  ✗ pwa build failed\${NC}"
  ERRORS=\$((ERRORS + 1))
fi
PREPUSH
  fi

  cat <<PREPUSH

echo ""
if [ "\$ERRORS" -eq 0 ]; then
  echo -e "\${GREEN}✓ All checks passed — safe to push\${NC}"
  exit 0
else
  echo -e "\${RED}✗ \$ERRORS check(s) failed — fix before pushing\${NC}"
  echo -e "\${YELLOW}Push anyway? [y/N]\${NC}"
  read -r CONFIRM
  if [ "\$CONFIRM" = "y" ] || [ "\$CONFIRM" = "Y" ]; then
    exit 0
  fi
  exit 1
fi
PREPUSH
}

# --- Write files ---

write_file() {
  local path="$1"
  local content="$2"

  if [ "$DRY_RUN" = true ]; then
    echo "--- $path (dry run) ---"
    echo "$content"
    echo ""
  else
    mkdir -p "$(dirname "$path")"
    echo "$content" > "$path"
    if [[ "$path" == *.sh ]]; then
      chmod +x "$path"
    fi
    echo "✓ $path"
  fi
}

echo "Generating Replit parity CI files..."
echo ""

if [ -z "$ONLY" ] || [ "$ONLY" = "workflow" ]; then
  write_file ".github/workflows/replit-parity.yml" "$(generate_workflow)"
fi

if [ -z "$ONLY" ] || [ "$ONLY" = "dockerfile" ]; then
  write_file "Dockerfile" "$(generate_dockerfile)"
  write_file ".dockerignore" "$(generate_dockerignore)"
fi

if [ -z "$ONLY" ] || [ "$ONLY" = "prepush" ]; then
  write_file "scripts/pre-push.sh" "$(generate_prepush)"
fi

echo ""
echo "Done. To install the pre-push hook:"
echo "  ln -sf ../../scripts/pre-push.sh .git/hooks/pre-push"
